# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-10397-emmk-prj1/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/axi_sd_bridge/include
    /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/include
    /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/axi/include
    /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/include
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/register_interface/include
    /home/riscv-contest/Documents/cva6-softcore-contest/core/include
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src
    /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/include/common_cells
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/hdl
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/hdl
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen
  } -define BRAM=BRAM {
      /opt/xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv -include {
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/axi_sd_bridge/include
    /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/include
    /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/axi/include
    /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/include
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/register_interface/include
    /home/riscv-contest/Documents/cva6-softcore-contest/core/include
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src
    /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/include/common_cells
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/hdl
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/hdl
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen
  } -define BRAM=BRAM {
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/zybo-z7-20.svh
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/include/common_cells/registers.svh
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/fpga-support/rtl/AsyncDpRam.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/fpga-support/rtl/AsyncThreePortRam.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/fpga-support/rtl/SyncDpRam.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/fpga-support/rtl/SyncDpRam_ind_r_w.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/fpga-support/rtl/SyncSpRamBeNx64.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/fpga-support/rtl/SyncThreePortRam.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/include/config_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/include/cv32a6_im_contest_config_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/include/riscv_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/include/ariane_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpnew_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/cf_math_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/acc_dispatcher.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/addr_decode.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/alu.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/amo_buffer.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_timer/apb_timer.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/register_interface/src/apb_to_reg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/axi/src/axi_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/tb/ariane_axi_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/src/ariane.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/tb/ariane_soc_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/tb/ariane_axi_soc_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane_peripherals_xilinx.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/ariane_regfile_ff.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/ariane_regfile_fpga.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/riscv-dbg/src/dm_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/axi2apb/src/axi2apb_64_32.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/axi_mem_if/src/axi2mem.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/axi_adapter.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/axi_slice/src/axi_ar_buffer.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/axi/src/axi_atop_filter.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/axi_slice/src/axi_aw_buffer.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/axi_slice/src/axi_b_buffer.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/axi/src/axi_demux.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/axi/src/axi_err_slv.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/axi/src/axi_id_prepend.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/tb/axi_intf.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/clint/axi_lite_interface.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/axi/src/axi_mux.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/axi_slice/src/axi_r_buffer.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/src/axi_riscv_atomics/src/axi_res_tbl.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/src/axi_riscv_atomics/src/axi_riscv_amos.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/src/axi_riscv_atomics/src/axi_riscv_amos_alu.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/src/axi_riscv_atomics/src/axi_riscv_atomics.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/src/axi_riscv_atomics/src/axi_riscv_atomics_wrap.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/src/axi_riscv_atomics/src/axi_riscv_lrsc.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/axi_shim.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/axi_slice/src/axi_single_slice.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/axi_slice/src/axi_w_buffer.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/axi/src/axi_xbar.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/axis_async_fifo.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/axis_gmii_rx.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/axis_gmii_tx.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/frontend/bht.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/bootrom/bootrom_32.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/bootrom/bootrom_64.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/branch_unit.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/frontend/btb.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/include/build_config_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/include/std_cache_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/cache_ctrl.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/cdc_2phase.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/clint/clint.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/tech_cells_generic/src/deprecated/cluster_clk_cells.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/commit_stage.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/compressed_decoder.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvxif_example/compressed_instr_decoder.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/controller.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvxif_example/include/cvxif_instr_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvxif_example/copro_alu.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/counter.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/csr_buffer.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/csr_regfile.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/include/wt_cache_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cva6.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cva6_accel_first_pass_decoder_stub.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cva6_fifo_v3.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/cva6_hpdcache_if_adapter.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/cva6_hpdcache_subsystem.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/cva6_hpdcache_wrapper.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/cva6_icache.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/cva6_icache_axi_wrapper.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cva6_mmu/cva6_mmu.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cva6_mmu/cva6_ptw.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cva6_rvfi_probes.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cva6_mmu/cva6_shared_tlb.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cva6_mmu/cva6_tlb.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvxif_compressed_if_driver.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvxif_example/cvxif_example_coprocessor.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvxif_fu.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvxif_issue_register_commit_if_driver.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/riscv-dbg/debug_rom/debug_rom.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/decoder.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/delta_counter.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/riscv-dbg/src/dm_csrs.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/riscv-dbg/src/dm_mem.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/riscv-dbg/src/dm_sba.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/riscv-dbg/src/dm_top.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/riscv-dbg/src/dmi_cdc.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/riscv-dbg/src/dmi_jtag.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/riscv-dbg/src/dmi_jtag_tap.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/dualmem_widen.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/dualmem_widen8.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/eth_mac_1g.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/eth_mac_1g_rgmii.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/eth_mac_1g_rgmii_fifo.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/ex_stage.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/exp_backoff.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/deprecated/fifo_v1.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/deprecated/fifo_v2.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/fifo_v3.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpnew_cast_multi.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpnew_classifier.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpnew_divsqrt_multi.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpnew_fma.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpnew_fma_multi.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpnew_noncomp.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpnew_opgroup_block.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpnew_opgroup_fmt_slice.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpnew_opgroup_multifmt_slice.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpnew_rounding.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpnew_top.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/fpu_wrap.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/framing_top.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/frontend/frontend.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_1hot_to_binary.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_amo.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cmo.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_core_arbiter.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl_pe.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_downsize.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_resize.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_upsize.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_decoder.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_demux.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_flush.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fxarb.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_lfsr.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_resp_demux.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_read.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_write.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memctrl.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_miss_handler.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_mux.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wmask_1rw.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_rrarb.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_rtab.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_1rw.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wbyteenable.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wbyteenable_1rw.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wmask.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wmask_1rw.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sync_buffer.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_uncached.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_plru.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_random.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_sel.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/id_stage.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/iddr.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvxif_example/instr_decoder.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/frontend/instr_queue.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/instr_realign.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/frontend/instr_scan.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/issue_read_operands.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/issue_stage.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/lfsr.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/lfsr_8bit.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/load_store_unit.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/load_unit.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/lsu_bypass.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/lzc.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/macro_decoder.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/miss_handler.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/mult.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/multiplier.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/oddr.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/perf_counters.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/rv_plic/rtl/plic_regmap.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/rv_plic/rtl/plic_top.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/pmp/src/pmp.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/pmp/src/pmp_data_if.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/pmp/src/pmp_entry.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/popcount.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/tech_cells_generic/src/deprecated/pulp_clk_cells.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/frontend/ras.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/register_interface/src/reg_intf.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/rgmii_core.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/rgmii_lfsr.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/rgmii_phy_if.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/rgmii_soc.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/rr_arb_tree.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/rstgen.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/rstgen_bypass.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/rv_plic/rtl/rv_plic_gateway.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/rv_plic/rtl/rv_plic_target.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/scoreboard.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/serdiv.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/shift_reg.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/spill_register.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/spill_register_flushable.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/common/local/util/sram.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/common/local/util/sram_cache.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/ariane-ethernet/ssio_ddr_in.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/std_cache_subsystem.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/std_nbdcache.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/store_buffer.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/store_unit.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/stream_arbiter.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/stream_arbiter_flushable.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/stream_demux.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/stream_mux.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/stream_register.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/tag_cmp.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/tech_cells_generic/src/rtl/tc_clk.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/common/local/util/tc_sram_fpga_wrapper.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/common/local/util/tc_sram_wrapper_cache_techno.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_timer/timer.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/src/unread.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/wt_axi_adapter.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/wt_cache_subsystem.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/wt_dcache.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/wt_dcache_ctrl.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/wt_dcache_mem.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/wt_dcache_missunit.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/wt_dcache_wbuffer.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/core/zcmt_decoder.sv
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/cva6_zybo_z7_20.sv
    }
      rt::read_verilog -include {
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/axi_sd_bridge/include
    /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/include
    /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/axi/include
    /home/riscv-contest/Documents/cva6-softcore-contest/core/cache_subsystem/hpdcache/rtl/include
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/register_interface/include
    /home/riscv-contest/Documents/cva6-softcore-contest/core/include
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src
    /home/riscv-contest/Documents/cva6-softcore-contest/vendor/pulp-platform/common_cells/include/common_cells
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/hdl
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/hdl
    /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen
  } -define BRAM=BRAM {
      ./.Xil/Vivado-10397-emmk-prj1/realtime/xlnx_axi_dwidth_converter_dm_master_stub.v
      ./.Xil/Vivado-10397-emmk-prj1/realtime/xlnx_axi_dwidth_converter_dm_slave_stub.v
      ./.Xil/Vivado-10397-emmk-prj1/realtime/xlnx_blk_mem_gen_stub.v
      ./.Xil/Vivado-10397-emmk-prj1/realtime/xlnx_clk_gen_stub.v
    }
      rt::read_vhdl -lib xpm /opt/xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_uart/src/apb_uart.vhd
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_uart/src/slib_clock_div.vhd
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_uart/src/slib_counter.vhd
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_uart/src/slib_edge_detect.vhd
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_uart/src/slib_fifo.vhd
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_uart/src/slib_input_filter.vhd
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_uart/src/slib_input_sync.vhd
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_uart/src/slib_mv_filter.vhd
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_uart/src/uart_baudgen.vhd
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_uart/src/uart_interrupt.vhd
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_uart/src/uart_receiver.vhd
      /home/riscv-contest/Documents/cva6-softcore-contest/corev_apu/fpga/src/apb_uart/src/uart_transmitter.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top cva6_zybo_z7_20
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-10397-emmk-prj1/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
