# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/cva6_fpga.runs/synth_1/cva6_zybo_z7_20.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-6509-emmk-prj1/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-4480} -limit 1000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {[Synth 8-5858]}  -new_severity {INFO} 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/cva6_fpga.cache/wt [current_project]
set_property parent.project_path /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/cva6_fpga.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.2 [current_project]
set_property ip_output_repo /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/cva6_fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/axi_sd_bridge/include
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/include
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/axi/include
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/include
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/register_interface/include
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/include
} [current_fileset]
set_property verilog_define BRAM=BRAM [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/zybo-z7-20.svh
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/include/common_cells/registers.svh
}
set_property file_type "Verilog Header" [get_files /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/zybo-z7-20.svh]
set_property is_global_include true [get_files /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/zybo-z7-20.svh]
set_property file_type "Verilog Header" [get_files /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/include/common_cells/registers.svh]
set_property is_global_include true [get_files /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/include/common_cells/registers.svh]
read_verilog -library xil_defaultlib -sv {
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/fpga-support/rtl/AsyncDpRam.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/fpga-support/rtl/AsyncThreePortRam.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/fpga-support/rtl/SyncDpRam.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/fpga-support/rtl/SyncDpRam_ind_r_w.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/fpga-support/rtl/SyncSpRamBeNx64.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/fpga-support/rtl/SyncThreePortRam.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/include/config_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/include/cv32a6_im_contest_config_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/include/riscv_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/include/ariane_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpnew_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/cf_math_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/acc_dispatcher.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/addr_decode.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/alu.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/amo_buffer.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_timer/apb_timer.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/register_interface/src/apb_to_reg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/axi/src/axi_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/tb/ariane_axi_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/src/ariane.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/tb/ariane_soc_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/tb/ariane_axi_soc_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane_peripherals_xilinx.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/ariane_regfile_ff.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/ariane_regfile_fpga.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/riscv-dbg/src/dm_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/axi2apb/src/axi2apb_64_32.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/axi_mem_if/src/axi2mem.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/axi_adapter.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/axi_slice/src/axi_ar_buffer.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/axi/src/axi_atop_filter.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/axi_slice/src/axi_aw_buffer.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/axi_slice/src/axi_b_buffer.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/axi/src/axi_demux.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/axi/src/axi_err_slv.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/axi/src/axi_id_prepend.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/tb/axi_intf.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/clint/axi_lite_interface.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/axi/src/axi_mux.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/axi_slice/src/axi_r_buffer.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/src/axi_riscv_atomics/src/axi_res_tbl.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/src/axi_riscv_atomics/src/axi_riscv_amos.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/src/axi_riscv_atomics/src/axi_riscv_amos_alu.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/src/axi_riscv_atomics/src/axi_riscv_atomics.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/src/axi_riscv_atomics/src/axi_riscv_atomics_wrap.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/src/axi_riscv_atomics/src/axi_riscv_lrsc.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/axi_shim.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/axi_slice/src/axi_single_slice.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/axi_slice/src/axi_w_buffer.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/axi/src/axi_xbar.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/axis_async_fifo.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/axis_gmii_rx.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/axis_gmii_tx.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/frontend/bht.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/bootrom/bootrom_32.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/bootrom/bootrom_64.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/branch_unit.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/frontend/btb.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/include/build_config_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/include/std_cache_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/cache_ctrl.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/cdc_2phase.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/clint/clint.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/tech_cells_generic/src/deprecated/cluster_clk_cells.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/commit_stage.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/compressed_decoder.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvxif_example/compressed_instr_decoder.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/controller.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvxif_example/include/cvxif_instr_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvxif_example/copro_alu.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/counter.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/csr_buffer.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/csr_regfile.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/include/wt_cache_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cva6.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cva6_accel_first_pass_decoder_stub.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cva6_fifo_v3.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/cva6_hpdcache_if_adapter.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/cva6_hpdcache_subsystem.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/cva6_hpdcache_wrapper.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/cva6_icache.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/cva6_icache_axi_wrapper.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cva6_mmu/cva6_mmu.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cva6_mmu/cva6_ptw.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cva6_rvfi_probes.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cva6_mmu/cva6_shared_tlb.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cva6_mmu/cva6_tlb.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvxif_compressed_if_driver.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvxif_example/cvxif_example_coprocessor.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvxif_fu.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvxif_issue_register_commit_if_driver.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/riscv-dbg/debug_rom/debug_rom.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/decoder.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/delta_counter.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/riscv-dbg/src/dm_csrs.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/riscv-dbg/src/dm_mem.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/riscv-dbg/src/dm_sba.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/riscv-dbg/src/dm_top.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/riscv-dbg/src/dmi_cdc.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/riscv-dbg/src/dmi_jtag.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/riscv-dbg/src/dmi_jtag_tap.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/dualmem_widen.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/dualmem_widen8.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/eth_mac_1g.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/eth_mac_1g_rgmii.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/eth_mac_1g_rgmii_fifo.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/ex_stage.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/exp_backoff.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/deprecated/fifo_v1.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/deprecated/fifo_v2.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/fifo_v3.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpnew_cast_multi.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpnew_classifier.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpnew_divsqrt_multi.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpnew_fma.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpnew_fma_multi.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpnew_noncomp.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpnew_opgroup_block.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpnew_opgroup_fmt_slice.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpnew_opgroup_multifmt_slice.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpnew_rounding.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpnew_top.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/fpu_wrap.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/framing_top.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/frontend/frontend.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_1hot_to_binary.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_amo.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cmo.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_core_arbiter.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl_pe.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_downsize.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_resize.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_upsize.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_decoder.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_demux.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_flush.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fxarb.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_lfsr.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_resp_demux.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_read.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_write.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memctrl.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_miss_handler.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_mux.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wmask_1rw.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_rrarb.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_rtab.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_1rw.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wbyteenable.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wbyteenable_1rw.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wmask.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wmask_1rw.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sync_buffer.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_uncached.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_plru.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_random.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_sel.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/id_stage.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/iddr.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvxif_example/instr_decoder.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/frontend/instr_queue.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/instr_realign.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/frontend/instr_scan.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/issue_read_operands.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/issue_stage.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/lfsr.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/lfsr_8bit.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/load_store_unit.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/load_unit.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/lsu_bypass.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/lzc.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/macro_decoder.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/miss_handler.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/mult.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/multiplier.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/oddr.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/perf_counters.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/rv_plic/rtl/plic_regmap.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/rv_plic/rtl/plic_top.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/pmp/src/pmp.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/pmp/src/pmp_data_if.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/pmp/src/pmp_entry.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/popcount.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/tech_cells_generic/src/deprecated/pulp_clk_cells.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/frontend/ras.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/register_interface/src/reg_intf.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/rgmii_core.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/rgmii_lfsr.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/rgmii_phy_if.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/rgmii_soc.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/rr_arb_tree.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/rstgen.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/rstgen_bypass.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/rv_plic/rtl/rv_plic_gateway.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/rv_plic/rtl/rv_plic_target.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/scoreboard.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/serdiv.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/shift_reg.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/spill_register.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/spill_register_flushable.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/common/local/util/sram.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/common/local/util/sram_cache.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/ariane-ethernet/ssio_ddr_in.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/std_cache_subsystem.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/std_nbdcache.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/store_buffer.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/store_unit.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/stream_arbiter.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/stream_arbiter_flushable.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/stream_demux.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/stream_mux.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/stream_register.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/tag_cmp.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/tech_cells_generic/src/rtl/tc_clk.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/common/local/util/tc_sram_fpga_wrapper.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/common/local/util/tc_sram_wrapper_cache_techno.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_timer/timer.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/vendor/pulp-platform/common_cells/src/unread.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/wt_axi_adapter.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/wt_cache_subsystem.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/wt_dcache.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/wt_dcache_ctrl.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/wt_dcache_mem.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/wt_dcache_missunit.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/cache_subsystem/wt_dcache_wbuffer.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/core/zcmt_decoder.sv
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/cva6_zybo_z7_20.sv
}
read_vhdl -library xil_defaultlib {
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_uart/src/apb_uart.vhd
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_uart/src/slib_clock_div.vhd
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_uart/src/slib_counter.vhd
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_uart/src/slib_edge_detect.vhd
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_uart/src/slib_fifo.vhd
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_uart/src/slib_input_filter.vhd
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_uart/src/slib_input_sync.vhd
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_uart/src/slib_mv_filter.vhd
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_uart/src/uart_baudgen.vhd
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_uart/src/uart_interrupt.vhd
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_uart/src/uart_receiver.vhd
  /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/src/apb_uart/src/uart_transmitter.vhd
}
read_ip -quiet /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.srcs/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.xci
set_property used_in_synthesis false [get_files -all /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_master/xlnx_axi_dwidth_converter_dm_master_ooc.xdc]

read_ip -quiet /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.srcs/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.xci
set_property used_in_synthesis false [get_files -all /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave.gen/sources_1/ip/xlnx_axi_dwidth_converter_dm_slave/xlnx_axi_dwidth_converter_dm_slave_ooc.xdc]

read_ip -quiet /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_blk_mem_gen/xlnx_blk_mem_gen.srcs/sources_1/ip/xlnx_blk_mem_gen/xlnx_blk_mem_gen.xci
set_property used_in_implementation false [get_files -all /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_blk_mem_gen/xlnx_blk_mem_gen.gen/sources_1/ip/xlnx_blk_mem_gen/xlnx_blk_mem_gen_ooc.xdc]

read_ip -quiet /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.srcs/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen.xci
set_property used_in_implementation false [get_files -all /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen_board.xdc]
set_property used_in_implementation false [get_files -all /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen.xdc]
set_property used_in_implementation false [get_files -all /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/xilinx/xlnx_clk_gen/xlnx_clk_gen.gen/sources_1/ip/xlnx_clk_gen/xlnx_clk_gen_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/constraints/zybo_z7_20.xdc
set_property used_in_implementation false [get_files /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/constraints/zybo_z7_20.xdc]

read_xdc /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/constraints/cva6_fpga.xdc
set_property used_in_implementation false [get_files /home/riscv-contest/Documents/cva6-softcore-contest-personal/corev_apu/fpga/constraints/cva6_fpga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top cva6_zybo_z7_20 -part xc7z020clg400-1 -global_retiming on
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cva6_zybo_z7_20.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file cva6_zybo_z7_20_utilization_synth.rpt -pb cva6_zybo_z7_20_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
